
	SELECT DISTINCT TOP 100 PERCENT
	A.FXMC AS 父项名称,
	A.FXBM AS 父项编码,
	A.BBH AS 版本号,
	A.ZXMC AS 子项名称,
	A.ZXBM AS 子项编码,
	A.ZXGG AS 子项规格,
	A.用量,
	A.备料比例,
	A.单价,
	A.材料总价,
	A.销售单价,
--计算成本材料
	SUM(CASE WHEN A.FMATERIALTYPE = 1 THEN A.材料总价 ELSE 0 END) OVER (PARTITION BY A.FXBM) AS 材料成本 
	
	
FROM
	(
	SELECT DISTINCT
		A.BBH,
		A.FXMC,
		A.FXBM,
		A.ZXMC,
		A.ZXBM,
		A.ZXGG,
		A.FNUMERATOR/ A.FDENOMINATOR AS 用量,
		1+A.FSCRAPRATE/100 AS 备料比例,
		D.单价,
		D.单价 * ( A.FNUMERATOR/ A.FDENOMINATOR ) * ( 1+A.FSCRAPRATE/100 ) AS 材料总价,
		C.销售单价,
		A.FMATERIALTYPE,
		A.ZZ
	FROM
		(
--抓取父项子项信息
	SELECT DISTINCT
		A.FUSEORGID,
		C.FNAME AS FXMC,
		A.FNUMBER AS BBH,
		B.FNUMBER AS FXBM,
		D.FNAME AS ZZ,
		TEMP.FNAME AS ZXMC,
		TEMP.FNUMBER AS ZXBM,
		TEMP.FSPECIFICATION AS ZXGG,
		TEMP.FENTRYID,
		TEMP.FMATERIALTYPE,
		TEMP.FSCRAPRATE,
		TEMP.FNUMERATOR,
		TEMP.FDENOMINATOR
	FROM
		T_ENG_BOM A
		LEFT JOIN T_BD_MATERIAL B ON A.FMATERIALID= B.FMATERIALID
		LEFT JOIN T_BD_MATERIAL_L C ON B.FMATERIALID= C.FMATERIALID
		LEFT JOIN T_ORG_ORGANIZATIONS_L D ON A.FUSEORGID= D.FORGID
		LEFT JOIN (
		SELECT DISTINCT
			B.FNUMBER,
			A.FENTRYID,
			A.FID,
			C.FNAME,
			C.FSPECIFICATION,
			A.FMATERIALTYPE,
			A.FSCRAPRATE,
			A.FNUMERATOR,
			A.FDENOMINATOR
		FROM
			T_ENG_BOMCHILD A
			LEFT JOIN T_BD_MATERIAL B ON B.FMATERIALID= A.FMATERIALID
			LEFT JOIN T_BD_MATERIAL_L C ON B.FMATERIALID= C.FMATERIALID 
		) TEMP ON TEMP.FID= A.FMASTERID 
	WHERE
		 A.FFORBIDSTATUS= 'A' 
		 AND A.FUSEORGID= '1915285'
		 --order by fxbm
	) A
		LEFT JOIN (
--选最新销售订单单价
	SELECT
		TEMP.FNUMBER,
		TEMP.FDATE,
		TEMP.FPRICE AS 销售单价
FROM
	(
--销售订单单价排序
	SELECT
		D.FNUMBER,
		A.FDATE,
		C.FPRICE,
		D.FUSEORGID,
		ROW_NUMBER ( ) OVER ( PARTITION BY B.FMATERIALID ORDER BY A.FDATE DESC ) AS rnk 
	FROM
		T_SAL_ORDER A
		LEFT JOIN T_SAL_ORDERENTRY B ON B.FID=A.FID
		LEFT JOIN T_SAL_ORDERENTRY_F C ON C.FENTRYID=B.FENTRYID
		LEFT JOIN T_BD_MATERIAL D ON D.FMATERIALID=B.FMATERIALID
		LEFT JOIN T_ORG_ORGANIZATIONS_L E ON D.FUSEORGID=E.FORGID
	WHERE
	 E.FORGID='1915285'
	)TEMP
	WHERE TEMP.RNK=1		
	) C ON A.FXBM= C.FNUMBER
		LEFT JOIN (
--抓取最新入库单单价
SELECT
		TEMP.FNUMBER,
		TEMP.F_BWBPRICE AS 单价,
		TEMP.FDATE,
		TEMP.XUHAO
	FROM
		(
--单价排序
		SELECT
			A.FNUMBER,
			C.F_BWBPRICE,
			C.XUHAO,
			C.FDATE
		FROM
			(
			SELECT
				ROW_NUMBER ( ) OVER ( PARTITION BY D.FNUMBER ORDER BY A.FDATE DESC ) AS XUHAO,
				A.FDATE,
				B.F_BWBPRICE,
				B.FMATERIALID
			FROM
				t_STK_InStock A
				INNER JOIN T_STK_INSTOCKENTRY B ON A.FID= B.FID
				LEFT JOIN T_BD_MATERIAL D ON D.FMATERIALID= B.FMATERIALID 
				LEFT JOIN T_ORG_ORGANIZATIONS_L E ON D.FUSEORGID=E.FORGID
	WHERE 
	E.FORGID='1915285'
			) C 
			LEFT JOIN T_BD_MATERIAL A ON A.FMATERIALID=C.FMATERIALID
		) TEMP 
	WHERE
		TEMP.XUHAO= 1 
	) D ON A.ZXBM= D.FNUMBER 
	)A 	
    
	WHERE
		a.ZXBM IS NOT NULL 
		AND A.FXBM='03.02.2001.00288'
	ORDER BY A.FXBM