SELECT Z.DUTY_DATE, DATEPART(WK, Z.DUTY_DATE - 1) AS WEEK, Z.人数, Z.总出勤时间,z.DEPT_CODE
FROM (SELECT Y.DUTY_DATE, COUNT(Y.A0190) AS '人数', SUM(出勤时间) AS '总出勤时间',y.DEPT_CODE
      FROM (SELECT  x.*
            FROM (SELECT A.A0188, B.A0190, B.A0101, B.DEPT_CODE, A.DUTY_DATE, SUM(A.K_ONHOURS + A.OVER_TIME) as '出勤时间'
                  FROM K_DAY A
                           INNER JOIN A01 B ON A.A0188 = B.A0188
--INNER JOIN B01 C ON B.DEPT_CODE=C.DEPT_CODE
                  WHERE DUTY_DATE >= DATEADD(DAY, 0, DATEDIFF(DAY, 0, GETDATE())) - 49
                    AND DUTY_DATE < DATEADD(DAY, 0, DATEDIFF(DAY, 0, GETDATE()))
                    AND B.DEPT_CODE IN ('107183201', '107183202', '10718260200')
                  GROUP BY A.A0188, B.A0190, B.A0101, B.DEPT_CODE, A.DUTY_DATE) X
            WHERE X.[出勤时间] <> 0) Y
--WHERE Y.[车间]='一部切割车间'
      GROUP BY Y.DUTY_DATE,y.DEPT_CODE) Z
ORDER BY Z.DUTY_DATE