-- 查询枚举类型

SELECT a.FID AS 枚举类型内码,b.FNAME AS 枚举类型名称,* FROM T_META_FORMENUM a
LEFT JOIN T_META_FORMENUM_L b ON a.FID=b.FID AND b.FLOCALEID=2052
--枚举类型名称
WHERE b.FNAME=N'枚举名称'



-- 查询某个枚举类型下的所有枚举项
SELECT a.FENUMID AS 枚举内码,b.FCAPTION AS 枚举名称,a.FVALUE AS 枚举值,* FROM T_META_FORMENUMITEM a
LEFT JOIN T_META_FORMENUMITEM_L b ON a.FENUMID=b.FENUMID AND b.FLOCALEID=2052
--枚举类型ID
WHERE a.FID='枚举类型内码'
ORDER BY a.FSEQ
