SELECT
    BBB.FMATERIALID,
    BBB.使用组织,
    BBB.币别,
    BBB.枚举名称,
    BBB.供应商,
    BBB.FAPPROVEDATE,
    BBB.XUHAO,
    BBB.F_KING_TDQWSDJ AS '替代前未税(本位币)单价',
    BBB.F_KING_TDQWLDM AS '替代前物料代码',
    BBB.F_KING_TDQWLMC AS '替代前物料名称',
    BBB.F_KING_TDQGZXH AS '替代前规格型号',
	BBB.F_KING_TDQGYS AS '替代前供应商'
FROM
(
	SELECT
	    D.FMATERIALID,
	    B.FNAME as 使用组织,
	    C.FNAME as 币别,
	    E.枚举名称,
	    F.FNAME AS 供应商,
	    A.FAPPROVEDATE ,
	    D.F_KING_TDQWSDJ,
	    D.F_KING_TDQWLDM,
	    D.F_KING_TDQWLMC,
	    D.F_KING_TDQGZXH,
	    D.F_KING_TDQGYS,
	    ROW_NUMBER ( ) OVER ( PARTITION BY D.FMATERIALID ORDER BY A.FAPPROVEDATE DESC ) AS XUHAO
	FROM t_PUR_PriceList A
	LEFT JOIN T_ORG_ORGANIZATIONS_L B ON A.FUSEORGID=B.FORGID
    LEFT JOIN T_BD_CURRENCY_l C ON A.FCURRENCYID=C.FPKID
	LEFT JOIN T_PUR_PRICELISTENTRY D ON D.FID=A.FID
	LEFT JOIN (
-- 查询某个枚举类型下的所有枚举项
SELECT a.FENUMID AS 枚举内码,b.FCAPTION AS 枚举名称,a.FVALUE FROM T_META_FORMENUMITEM a
LEFT JOIN T_META_FORMENUMITEM_L b ON a.FENUMID=b.FENUMID AND b.FLOCALEID=2052
--枚举类型ID
WHERE a.FID='2ac5f5c7-51e1-4d43-8caa-41064c9b3a0a'
) E ON E.FVALUE=A.FPRICETYPE
	LEFT JOIN t_BD_Supplier_l F ON F.FSUPPLIERID=A.FSUPPLIERID
	WHERE B.FNAME='芜湖长信新型显示器件有限公司')BBB
	WHERE BBB.XUHAO=1