SELECT
B.FNUMBER 物料编码,
C.FNAME 物料名称,
FSPECIFICATION 规格型号,
SUM(FREQQTY) 申请数量,
F.FNAME 采购员,
FAPPLICATIONDATE 申请日期,
H.FNAME 申请组织,
A.F_KFCG 开发采购,
FNOTE 备注,
G.FNAME 申请单位,
E.FNAME 单据类型,
FBILLNO 单据编号
FROM T_PUR_ReqEntry A
INNER JOIN T_PUR_Requisition AB ON A.FID=AB.FID
INNER JOIN T_BD_MATERIAL B ON A.FMATERIALID=B.FMATERIALID
INNER JOIN T_BD_MATERIAL_L C ON B.FMATERIALID=C.FMATERIALID AND C.FLOCALEID=2052
INNER JOIN t_bd_MaterialPurchase D ON A.FMATERIALID=D.FMATERIALID
LEFT JOIN T_BAS_BILLTYPE_L E ON AB.FBILLTYPEID=E.FBILLTYPEID AND E.FLOCALEID=2052
LEFT JOIN V_BD_BUYER_L F ON D.FPURCHASERID=F.FID AND F.FLOCALEID=2052
LEFT JOIN T_BD_UNIT_L G ON A.FUNITID=G.FUNITID AND G.FLOCALEID=2052
INNER JOIN T_ORG_ORGANIZATIONS_L H ON FAPPLICATIONORGID=H.FORGID AND H.FLOCALEID=2052
WHERE FNUMBER NOT IN
(SELECT FNUMBER FROM t_PUR_PriceListEntry D
INNER JOIN T_BD_MATERIAL ON T_BD_MATERIAL.FMATERIALID=D.FMATERIALID)
--and FNUMBER like '%#FMaterialNumber#%' and C.FNAME like '%#FMaterialName#%'
--and FSPECIFICATION like '%#FSPECIFICATION#%'
and FAPPLICATIONDATE >= '2024-3-1'
and FAPPLICATIONDATE <= '2024-3-13'
and H.FNAME like '第一事业部'
AND AB.FDOCUMENTSTATUS = 'C' AND AB.FCANCELSTATUS = 'A' AND AB.FCLOSESTATUS = 'A' AND FMANUALCLOSE = 0
GROUP BY B.FNUMBER,C.FNAME,FSPECIFICATION,F.FNAME,A.F_KFCG,FAPPLICATIONDATE,H.FNAME,FNOTE,G.FNAME,FBILLNO,E.FNAME