

SELECT
DISTINCT
	TEMP5.FASSETNO AS 资产编码,
	TEMP5.ZZMC AS 资产名称,
	TEMP5.FNAME1 AS 资产位置,
	TEMP5.FACCTDATE AS 入账日期,
	TEMP5.FBEGINUSEDATE AS 使用时间,
	TEMP5.FALLOCRATIO AS 分配比例,
	TEMP5.FORGVAL AS 资产原值,
	TEMP5.FNETVALUE AS 资产净值,
	TEMP5.FACCUMDEPR AS 累计折旧,
	TEMP5.FDEPR AS 本期折旧,
	TEMP5.SYBM AS 使用部门,
	a.FNAME  AS 所属组织
FROM (
	SELECT 
		TEMP4.FASSETNO,
		H.FNAME as ZZMC,
		TEMP4.FNAME1,
		I.FACCTDATE,
		TEMP4.FBEGINUSEDATE,
		TEMP4.FALLOCRATIO,
		TEMP4.FLOCALEID,
		temp4.FOWNERORGID,
		TEMP4.FDOCUMENTSTATUS,
		I.FORGVAL,
		J.FNETVALUE,
		J.FACCUMDEPR,
		J.FDEPR,
		TEMP4.FALTERID,
		TEMP4.FFORBIDSTATUS,
		TEMP4.FID,
		TEMP4.FR,
		TEMP4.SYBM,
		TEMP4.FPKID 
	FROM (
		SELECT
			TEMP3.FASSETNO,
			TEMP3.FNAME1,
			TEMP3.FALTERID,
			TEMP3.FBEGINUSEDATE,
			TEMP3.FLOCALEID,
			TEMP3.FFORBIDSTATUS,
			TEMP3.FDOCUMENTSTATUS,
			G.FALLOCRATIO,
			G.FID,
			E1.FNAME AS FR,
			TEMP3.FNAME AS SYBM,
			TEMP3.FPKID,
			temp3.FOWNERORGID 
		FROM (
			SELECT
				TEMP2.FASSETNO,
				TEMP2.FNAME1,
				TEMP2.FBEGINUSEDATE,
				TEMP2.FLOCALEID,
				temp2.FALTERID,
				E.FDEPTID,
				E.FPKID,
				E.FNAME ,
				TEMP2.FDOCUMENTSTATUS,
				TEMP2.FFORBIDSTATUS,
				temp2.FOWNERORGID 
			FROM (
				SELECT
					TEMP.FID,
					TEMP.FNAME1,
					TEMP.FALTERID,
					TEMP.FASSETNO,
					TEMP.FLOCALEID,
					TEMP.FFORBIDSTATUS,
					D.FUSEDEPTID,
					D.FDOCUMENTSTATUS,
					D.FBEGINUSEDATE,
					D.FOWNERORGID 
				FROM (
					SELECT
						A.FALTERID,
						A.FID,
						A.FASSETNO,
						B.FNAME AS FNAME1,
						C.FID AS FPOSITIONID,
						B.FLOCALEID,
						C.FFORBIDSTATUS 
					FROM
						T_FA_CARDDETAIL A
						LEFT JOIN T_FA_POSITION_L B ON B.FID = A.FPOSITIONID
						LEFT JOIN T_FA_POSITION C ON C.FMASTERID = B.FID 
					
				) TEMP
				LEFT JOIN T_FA_CARD D ON D.FALTERID = TEMP.FALTERID
			) TEMP2
			LEFT JOIN T_BD_DEPARTMENT_L E ON E.FDEPTID = TEMP2.FUSEDEPTID
		) TEMP3
		LEFT JOIN t_fa_allocation G ON G.FID = TEMP3.FDEPTID
	  LEFT JOIN T_BD_DEPARTMENT BD on G.Fusedeptid = BD.FDEPTID 
		LEFT JOIN T_ORG_ORGANIZATIONS_L ORG on ORG.forgid =BD.F_SUBORGID
		LEFT JOIN T_BD_DEPARTMENT_L E1 on G.Fusedeptid=E1.fdeptid
	) TEMP4
	LEFT JOIN T_FA_CARD_L H ON H.FALTERID= TEMP4.FALTERID
	LEFT JOIN T_FA_FINANCE I ON I.FALTERID= TEMP4.FALTERID
	LEFT JOIN V_FA_LASTBALANCE J ON J.FFINANCEID= I.FFINANCEID 
) TEMP5
LEFT JOIN (
	SELECT DISTINCT a.Fusedeptid, b.F_SUBORGID, c.fname, d.FNAME AS syb 
	FROM T_FA_ALLOCATION a
	LEFT JOIN T_BD_DEPARTMENT b ON a.Fusedeptid = b.FDEPTID 
	LEFT JOIN T_ORG_ORGANIZATIONS_L c ON c.forgid = b.F_SUBORGID
	LEFT JOIN T_BD_DEPARTMENT_L d ON a.Fusedeptid = d.fdeptid
) a ON a.syb = temp5.SYBM
WHERE
1=1
	AND TEMP5.FFORBIDSTATUS = 'A' 
	AND TEMP5.FDOCUMENTSTATUS = 'C' 
	AND (
		a.FNAME = '第一事业部'
		OR a.FNAME = '第二事业部'
		OR a.FNAME = '第三事业部'
		OR a.FNAME = '第五事业部'
		OR a.FNAME = '(原)第五事业部'
		OR a.FNAME = '工程中心'
	)