SELECT DISTINCT
		C.FNAME AS FXMC,
		B.FNUMBER AS FXBM,
		B.FMATERIALID,
		A.FMASTERID,
		D.FNAME AS ZZ
	FROM
		T_ENG_BOM A
		LEFT JOIN T_BD_MATERIAL B ON A.FMATERIALID= B.FMATERIALID
		LEFT JOIN T_BD_MATERIAL_L C ON B.FMATERIALID= C.FMATERIALID
		LEFT JOIN T_ORG_ORGANIZATIONS_L D ON A.FUSEORGID= D.FORGID
	WHERE
		--D.FNAME= '车载事业部' 
		A.FFORBIDSTATUS= 'A' 
		AND B.FNUMBER='03.01.1002.00092-CK'
		--A.FID='3678046'
-- SELECT * FROM T_ENG_BOM WHERE FMASTERID='2409224'
-- SELECT * FROM T_ENG_BOMCHILD
-- WHERE 
		SELECT
			B.FNUMBER,
			--A.FENTRYID,
			A.FID,
			C.FNAME
			--C.FSPECIFICATION 
		FROM
			T_ENG_BOMCHILD A
			LEFT JOIN T_BD_MATERIAL B ON B.FMATERIALID= A.FMATERIALID
			LEFT JOIN T_BD_MATERIAL_L C ON B.FMATERIALID= C.FMATERIALID
	WHERE
		-- A.FFORBIDSTATUS= 'A' 
		--B.FNUMBER='03.01.1002.00092-CK'
		 A.FID='2409224'
