WITH SCLL AS (SELECT SUM(SCLL_S.FACTUALQTY * ML.F_MJM2) AS 'SCLL总投入'
              FROM T_PRD_PICKMTRL SCLL
                       INNER JOIN T_PRD_PICKMTRLDATA SCLL_S ON SCLL.FID = SCLL_S.FID
                       INNER JOIN T_BD_MATERIAL ML ON ML.FMATERIALID = SCLL_S.FMATERIALID
              WHERE SCLL.FSTOCKID0 = '103748' --1部原料仓(本部)
                AND (
                  (DAY(GETDATE()) = 1 AND DAY(DATEADD(DAY, -1, GETDATE())) = DAY(DATEADD(MONTH, -1, GETDATE())) AND
                   DATEPART(YEAR, GETDATE()) = DATEPART(YEAR, SCLL.FDATE) AND
                   DATEPART(MONTH, GETDATE()) = DATEPART(MONTH, SCLL.FDATE))
                      OR (DAY(GETDATE()) != 1 AND MONTH(DATEADD(DAY, -1, GETDATE())) = MONTH(GETDATE()) AND
                          DATEPART(YEAR, GETDATE()) = DATEPART(YEAR, SCLL.FDATE) AND
                          DATEPART(MONTH, GETDATE()) = DATEPART(MONTH, SCLL.FDATE))
                      OR (DATEPART(YEAR, DATEADD(DAY, -1, GETDATE())) = DATEPART(YEAR, SCLL.FDATE) AND
                          DATEPART(MONTH, DATEADD(DAY, -1, GETDATE())) = DATEPART(MONTH, SCLL.FDATE))
                  )
                AND DAY(SCLL.FDATE) < DAY(GETDATE())),
     ZJDB AS (SELECT SUM(ZJDB_S.FQTY * ML.F_MJM2) AS 'ZJDB总投入'
              FROM T_STK_STKTRANSFERIN ZJDB
                       INNER JOIN T_STK_STKTRANSFERINENTRY ZJDB_S ON ZJDB.FID = ZJDB_S.FID
                       INNER JOIN T_BD_MATERIAL ML ON ML.FMATERIALID = ZJDB_S.FMATERIALID
              WHERE ZJDB.F_KING_SRCSTOCKID = '103748' --1部原料仓(本部)
                AND (
                  (DAY(GETDATE()) = 1 AND DAY(DATEADD(DAY, -1, GETDATE())) = DAY(DATEADD(MONTH, -1, GETDATE())) AND
                   DATEPART(YEAR, GETDATE()) = DATEPART(YEAR, ZJDB.FDATE) AND
                   DATEPART(MONTH, GETDATE()) = DATEPART(MONTH, ZJDB.FDATE))
                      OR (DAY(GETDATE()) != 1 AND MONTH(DATEADD(DAY, -1, GETDATE())) = MONTH(GETDATE()) AND
                          DATEPART(YEAR, GETDATE()) = DATEPART(YEAR, ZJDB.FDATE) AND
                          DATEPART(MONTH, GETDATE()) = DATEPART(MONTH, ZJDB.FDATE))
                      OR (DATEPART(YEAR, DATEADD(DAY, -1, GETDATE())) = DATEPART(YEAR, ZJDB.FDATE) AND
                          DATEPART(MONTH, DATEADD(DAY, -1, GETDATE())) = DATEPART(MONTH, ZJDB.FDATE))
                  )
                AND DAY(ZJDB.FDATE) < DAY(GETDATE()))

SELECT SCLL总投入 + ZJDB总投入 AS '总投入'
FROM SCLL,
     ZJDB
