--暂估
WITH ZG AS
(
select
COUNT(*) as 总数
from(
-- 暂估，取所有的：
-- 付款核销状态不等于已完全
-- 立账类型等于暂估
-- 生成方式为空
-- 表体开票核销状态不等于完全
SELECT
A.FBILLNO AS 单据号,
FBUYIVQTY AS 采购发票数量,
A.FWRITTENOFFSTATUS AS 付款核销状态,
A.FSETACCOUNTTYPE AS 立账类型,
A.FBYVERIFY AS 生成方式,
B.FOPENSTATUS AS 表体开票核销状态--T_AP_PAYABLEENTRY
FROM
T_AP_PAYABLE A
LEFT JOIN T_AP_PAYABLEENTRY B ON A.FID = B.FID
WHERE
A.FWRITTENOFFSTATUS <> 'C'
AND A.FDOCUMENTSTATUS='C'
AND A.FSETACCOUNTTYPE = '2'
AND A.FBYVERIFY ='0'
AND B.FOPENSTATUS <> 'C'
AND A.FPAYORGID IN ('1', '100329', '100330', '100331', '100332', '3798064', '4355331')
) AA
),
--暂估已推发票
ZG1 AS
(
select
COUNT(*) as 总数
from(
-- 发票
SELECT
A.FBILLNO AS 单据号,
FBUYIVQTY AS 采购发票数量,
A.FWRITTENOFFSTATUS AS 付款核销状态,
A.FSETACCOUNTTYPE AS 立账类型,
A.FBYVERIFY AS 生成方式,
B.FOPENSTATUS AS 表体开票核销状态--T_AP_PAYABLEENTRY
FROM
T_AP_PAYABLE A
LEFT JOIN T_AP_PAYABLEENTRY B ON A.FID = B.FID
WHERE
A.FWRITTENOFFSTATUS <> 'C'
AND A.FDOCUMENTSTATUS='C'
AND A.FSETACCOUNTTYPE = '2'
AND A.FBYVERIFY ='0'
AND B.FOPENSTATUS <> 'C'
AND B.FBUYIVQTY<>'0'
AND A.FPAYORGID IN ('1', '100329', '100330', '100331', '100332', '3798064', '4355331')
) AA
)

SELECT
ZG.总数-ZG1.总数 AS 暂估未推发票
FROM ZG,ZG1